export const EXPERT_CATEGORIES = [
  'Journalism & Media',
  'Communications & Public Relations',
  "Gender Equality & Women's Rights",
  'Human Rights & Advocacy',
  'Governance & Public Policy',
  'Law & Justice',
  'Health & Public Health',
  'Education & Research',
  'Business & Economics',
  'Science & Technology',
  'Environment & Climate',
  'Agriculture & Food Systems',
  'Arts, Culture & Entertainment',
  'Social Development & Disability',
  'Other',
] as const;
